### Post Order
POST http://localhost:3003/order/create
# POST https://shopper-teste.herokuapp.com/order/create
Content-Type: application/json

{
    "customer_name": "Paulo",
    "delivery_date": "22/02/2020",
    "products": [{
        "amount":1,
        "id_product":"18"
    }]
}

### Get Products
# GET http://localhost:3003/product

GET https://shopper-teste.herokuapp.com/product